name: Herfa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI and design
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.5
  flutter_image_compress: ^2.0.0
  
  # State management
  provider: ^6.1.2
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  
  # Networking and data
  http: ^1.1.0
  dio: ^5.7.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  
  # Utilities
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  fluttertoast: ^8.2.0
  injectable: ^2.4.4
  
  # Error tracking
  sentry_flutter: ^7.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
