// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5e-cmDDd52_Xfg7gZXpa4GfB-Ng1O19s',
    appId: '1:633074425550:web:db114a5124f5aa7a85fa9f',
    messagingSenderId: '633074425550',
    projectId: 'herfa-7628d',
    authDomain: 'herfa-7628d.firebaseapp.com',
    storageBucket: 'herfa-7628d.firebasestorage.app',
    measurementId: 'G-MGC8Y8T6N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBquVlvprPUncCyGjRAfM3eYXGd97lc3pU',
    appId: '1:633074425550:android:480a608c2c03ffea85fa9f',
    messagingSenderId: '633074425550',
    projectId: 'herfa-7628d',
    storageBucket: 'herfa-7628d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYACA2iR6srp3sF4CA2nc50UYWZmzmwbo',
    appId: '1:633074425550:ios:8b4923cbda2ae64b85fa9f',
    messagingSenderId: '633074425550',
    projectId: 'herfa-7628d',
    storageBucket: 'herfa-7628d.firebasestorage.app',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYACA2iR6srp3sF4CA2nc50UYWZmzmwbo',
    appId: '1:633074425550:ios:8b4923cbda2ae64b85fa9f',
    messagingSenderId: '633074425550',
    projectId: 'herfa-7628d',
    storageBucket: 'herfa-7628d.firebasestorage.app',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5e-cmDDd52_Xfg7gZXpa4GfB-Ng1O19s',
    appId: '1:633074425550:web:7e1cb27e18b3f6d185fa9f',
    messagingSenderId: '633074425550',
    projectId: 'herfa-7628d',
    authDomain: 'herfa-7628d.firebaseapp.com',
    storageBucket: 'herfa-7628d.firebasestorage.app',
    measurementId: 'G-SRLX1DGWSK',
  );

}